name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        # Install Cygwin packages
        cygwin: 1
    - name: Build
      run: gcc -o rcon.exe rcon.c
  release:
    runs-on: ubuntu-latest
    needs: [build]
  
    steps:
    - uses: actions/checkout@master
    - name: Create release
      uses: Roang-zero1/github-create-release-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create GitHub release
      uses: Roang-zero1/github-upload-release-artifacts-action@master
      with:
        args: rcon.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
