name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        # Install Cygwin packages
        cygwin: 1
    - name: Build
      run: gcc -o rcon.exe rcon.c
    - name: Release & Assets
      uses: Hs1r1us/Release-AIO@v1.0
      with:
        # The name of the tag
        tag_name: 'builded'
